
# Use this example for the proxy document server running at 'backendserver-address'
# into the virtual directory 'documentserver-virtual-path'.
# Replace {{TRAEFIK_HOST}} with a name or an ip of the traefik server

defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
    address = ":80"

[file]

[backends]
  [backends.docservice]
    [backends.docservice.servers.backendserver-address]
    url = "http://backendserver-address/"

[frontends]
  [frontends.docservice]
  backend = "docservice"
  passHostHeader = true

    [frontends.docservice.headers.customrequestheaders]
    X-Forwarded-Prefix = "/documentserver-virtual-path"
  
    [frontends.docservice.routes.vpath]
<<<<<<< HEAD
    rule = "PathPrefixStrip:/documentserver-virtual-path/"
=======
    rule = "PathPrefixStrip:/documentserver-virtual-path/"
>>>>>>> parent of 4d5d6bd... Fix endline
